name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  tyk-sync-version:
    description: 'The version of Tyk Sync'
    required: true
#    default: ''
#outputs:
#  time: # id of output
#    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'
